### ISSUE TITLE
Generate SfM statistics

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/openMVG#102]
Currently we print all information, but it's not easy to parse and compare reconstruction results.

Generate a json file with all useful information about the reconstruction:
- [x] nb input images
- [x] nb reconstructed cameras
- [x] nb 3D points
- [x] reprojection error
- [x] input tracks length histogram
- [x] observations length histogram
- [x] time
- [x] computer nb CPUs, CPU frequency, RAM size

All the parameters of the reconstruction are not saved here. They should be stored before calling openMVG because all previous steps can have an impact.

Other tasks:
- [x] make the boost dependency independent of the voctree

[Boost property tree](http://www.boost.org/doc/libs/1_60_0/doc/html/property_tree.html)

**Comment by pmoulon** [comment]
There is already some of those information in the html report file.
With reprojection error for each view....
You can certainly find some content to use in it:
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_report.hpp#L18

**Comment by fabiencastan** [comment]
@caymard status?

**Comment by caymard** [comment]
Work done in this [branch](https://github.com/poparteu/openMVG/tree/popart_sfmstats)

**Comment by fabiencastan** [comment]
Can you create a PR?

**Comment by caymard** [comment]
#187 created

**Comment by simogasp** [comment]
what about those 3 missing points? are they done?

**Comment by caymard** [comment]
@simogasp time is now in (just have to check with the openMVG::system::Timer)

for cpu/ram info, I have this commands that return values:
- CPU cores : `nproc`
- CPU frequency (MHz) : `lscpu | grep "CPU MHz" | awk '{print $3}'`
- RAM size (kB) : `cat /proc/meminfo | grep MemTotal | awk '{print $2}'`

I could call them with `std::system(...)`. But for we have to make a condition for Mac/Windows.

**Comment by simogasp** [comment]
`#ifdef __linux__`

**Comment by caymard** [comment]
Actual version of stat json:
```json
{
    "sfm":
    {
        "inputtracks_histogram":
        {
            "2": "1527",
            "3": "578",
            "4": "293",
            "5": "183",
            "6": "106",
            "7": "72",
            "8": "70",
            "9": "46",
            "10": "32",
            "11": "30",
            "12": "25",
            "13": "12",
            "14": "9",
            "15": "14",
            "16": "13",
            "17": "10",
            "18": "10",
            "19": "2",
            "24": "1"
        },
        "views": "25",
        "poses": "25",
        "points": "2597",
        "observations_histogram":
        {
            "2": "1247",
            "3": "534",
            "4": "287",
            "5": "157",
            "6": "93",
            "7": "72",
            "8": "52",
            "9": "41",
            "10": "27",
            "11": "22",
            "12": "19",
            "13": "11",
            "14": "7",
            "15": "11",
            "16": "4",
            "17": "8",
            "18": "4",
            "19": "0",
            "20": "0",
            "21": "0",
            "22": "0",
            "23": "1"
        },
        "time": "5.028"
    },
    "hardware":
    {
        "cpu":
        {
            "cores": "16",
            "freq": "3300.000"
        },
        "ram":
        {
            "size": "32870524"
        }
    }
}
```

**Comment by fabiencastan** [comment]
Instead of subprocess of external commands, you can use the system API.

Something like that for RAM: https://github.com/tuttleofx/TuttleOFX/blob/develop/libraries/tuttle/src/tuttle/common/system/memoryInfo.cpp#L21

Something like that for nproc: http://stackoverflow.com/questions/4586405/get-number-of-cpus-in-linux-using-c

**Comment by pmoulon** [comment]
Another "easy" solution for nproc is to use OpenMP if it is supported
```
  #ifdef OPENMVG_USE_OPENMP
    nb_threads_ = omp_get_max_threads();
  #endif // OPENMVG_USE_OPENMP
```

**Comment by caymard** [comment]
Thanks for the hint
