### ISSUE TITLE
[cmake] generate "config.hpp" for external usage

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/openMVG#192]
http://www.vtk.org/Wiki/CMake:How_To_Write_Platform_Checks
https://cmake.org/cmake/help/v3.0/command/configure_file.html

It will ensure that all defines are correctly propagated for external usage.

**Comment by simogasp** [comment]
https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

**Comment by simogasp** [comment]
* [ ] Among other things I think it would be better to rename all the HAVE_* with OPENVG_HAVE_* to avoid conflicts.
* [ ] And remove the #ifdef HAVE_* at the very beginning of the files eg https://github.com/alicevision/openMVG/blob/popart_develop/src/openMVG/sfm/AlembicExporter.hpp#L1 (my bad!) and let cmake decide whether to include or not the file(s) in the compilation (hence, remove the GLOB RECURSE and explicitly list the files to compile)
