### ISSUE TITLE
[evalQuality] repository in poparteu

### ISSUE THREAD

**Issue by simogasp** [alicevision/openMVG#200]
- [x] fork @caymard repository into poparteu https://github.com/caymard/SfM_quality_evaluation (only @fabiencastan  can do it)
- [x] merge dev into master
- [x] change travis so that it clones from poparteu

**Comment by fabiencastan** [comment]
I fixed the permission problem.

**Comment by simogasp** [comment]
didn't see that we had already the repository, and that it was up-to-date. So only travis need to be changed now.

**Comment by simogasp** [comment]
done in 7db25ff150b361a6580e29b0431ed7a49e032e0d
