### ISSUE TITLE
openMVG2CMPMVS remap option

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/openMVG#32]
Add a remap path option (linux/windows conversion).

**Comment by fabiencastan** [comment]
and use symlink on linux

**Comment by eprana** [comment]
@fabiencastan Can you describe it more precisely ?

**Comment by fabiencastan** [comment]
CMPMVS use absolute paths and works only on windows.
If your source files have moved or if your previous steps were computed on linux, you have to remap the paths.
Currently it's hardcoded in popart_demo, so we need to use a dynamic argument instead.

https://github.com/poparteu/openMVG/blob/popart_demo/src/software/SfM/main_openMVG2CMPMVS.cpp#L154

**Comment by fabiencastan** [comment]
Doesn't make sense anymore.
